name: CI

on:
  push:
    branches: [main, "feat/**", "fix/**"]
  pull_request:

permissions:
  contents: read

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      CYPRESS_INSTALL_BINARY: 0
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn eslint:test
      - name: i18n
        run: yarn i18n:check
      - name: Unit tests
        run: yarn test --ci
      - name: Build
        run: yarn build
